# # ################### Production apply ##################################
# name: 'Install Infra Production'

# on:
#   push:
#     branches:
#     - master

# jobs:

#   apply-prod:
#     name: 'Install Infra Production'
#     runs-on: ubuntu-latest
#     environment: prod
# #    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

#     defaults:
#       run:
#         shell: bash
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
    
#     - name: apply-production
#       uses: dflook/terraform-apply@v1
#       env:
#         GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
#         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY }}
#         TERRAFORM_HTTP_CREDENTIALS: |
#           github.com/ebomart=${{ secrets.CI_USER}}:${{ secrets.CI_TOKEN}}
#       with:
#         path: ./
#         var_file: environment/production/variables.tfvars
#         label: production
#         backend_config_file: environment/production/gcs-bucket.tfvars