# name: 'Install Infra Staging'

name: 'Install Infra Staging'
on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'environment'     
          required: true
          default: stage

################## Staging apply ##################################
jobs:

  apply-staging:
    name: 'Install Infra Staging'
    runs-on: ubuntu-latest
    environment: staging
#    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: apply-staging
      uses: dflook/terraform-apply@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/ebomart=${{ secrets.CI_USER}}:${{ secrets.CI_TOKEN}}
      with:
        path: ./
        var_file: environment/staging/variables.tfvars
        label: staging
        backend_config_file: environment/staging/gcs-bucket.tfvars

