name: 'Install Infra Dev'
on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: environment   
          required: true
          default: dev

jobs:

################### Dev apply ##################################

  apply-dev:
    name: 'Install Infra DEV'
    runs-on: [ubuntu-latest]
    environment: dev
    # if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: apply-dev
      uses: dflook/terraform-apply@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        GOOGLE_ENCRYPTION_KEY: ${{ secrets.GOOGLE_ENCRYPTION_KEY }}
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/ebomart=${{ secrets.CI_USER}}:${{ secrets.CI_TOKEN}}
        TF_VAR_ssl_server_certificate: ${{ secrets.SERVER_CERTIFICATE}}
        TF_VAR_ssl_server_key: ${{ secrets.SERVER_KEY }}
        TF_VAR_jumpbox_docker_registry_password: ${{ secrets.GRP_CI_TOKEN}}
        TF_VAR_cloudflare_email: ${{ secrets.CLOUDFLARE_EMAIL }}
        TF_VAR_cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }} 
        TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        TF_VAR_auth0_credentials: ${{ secrets.AUTH0_CREDS_DEV }} 
      with:
        path: ./
        var_file: environment/dev/variables.tfvars
        label: dev
        backend_config_file: environment/dev/gcs-bucket.tfvars
        # variables: | 
        #   prometheus_htpasswd: ${{ secrets.PROMETHEUS_HTPASSWD }}
        auto_approve: true
