name: 'Install Infra Prod'
on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'environment'     
          required: true
          default: prod
jobs:

  apply-prod:
    name: 'Install Infra IBO'
    runs-on: ubuntu-latest
    environment: prod

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: apply-production
      uses: dflook/terraform-apply@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY_IBO }}
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/ebomart=${{ secrets.CI_USER}}:${{ secrets.CI_TOKEN}}
        TF_VAR_ssl_server_certificate: ${{ secrets.SERVER_CERTIFICATE}}
        TF_VAR_ssl_server_key: ${{ secrets.SERVER_KEY }}
        TF_VAR_jumpbox_docker_registry_password: ${{ secrets.GRP_CI_TOKEN}}
      with:
        path: ./
        var_file: environment/production/variables.tfvars
        label: prod
        backend_config_file: environment/production/gcs-bucket.tfvars
        auto_approve: true
