name: 'Install Infra'

on:
  push:
    branches:
    - master

jobs:
  apply:
    name: 'Install Infra DEV'
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: apply-dev
      uses: dflook/terraform-apply@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      with:
        path: ./
        var_file: environment/dev/variables.tfvars
        label: dev
        backend_config_file: environment/dev/gcs-bucket.tfvars

################### Staging apply ##################################

  apply-staging:
    name: 'Install Infra Staging'
    runs-on: ubuntu-latest
    environment: staging
#    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: apply-staging
      uses: dflook/terraform-apply@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      with:
        path: ./
        var_file: environment/staging/variables.tfvars
        label: staging
        backend_config_file: environment/staging/gcs-bucket.tfvars


################### Sandbox apply ##################################

  apply-sandbox:
    name: 'Install Infra Sandbox'
    runs-on: ubuntu-latest
    environment: sandbox
#    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: apply-sandbox
      uses: dflook/terraform-apply@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      with:
        path: ./
        var_file: environment/sandbox/variables.tfvars
        label: sandbox
        backend_config_file: environment/sandbox/gcs-bucket.tfvars

################### Production apply ##################################

  apply-prod:
    name: 'Install Infra Production'
    runs-on: ubuntu-latest
    environment: prod
#    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: apply-production
      uses: dflook/terraform-apply@v1
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      with:
        path: ./
        var_file: environment/production/variables.tfvars
        label: production
        backend_config_file: environment/production/gcs-bucket.tfvars

